name: "📝 Template Request"
description: Submit a request for a new project template.
title: "[TEMPLATE REQUEST] - <title>"
labels: ["template request"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us understand your template request better.
  
  - type: dropdown
    id: domain
    attributes:
      label: "What domain will the project template be based on?"
      options:
        - "API"
        - "Competitive Programming"
        - "FullStack"
        - "DataScience"
        - "Web3"
        - "Portfolio-Websites"
        - "CMS"
        - "Clones"
        - "Microservices"
        - "Blockchain"
        - "DevOps"
        - "Others (please specify in the details)"
  
  - type: textarea
    id: preferred_domain
    attributes:
      label: "If 'Others', please specify the preferred domain."
      placeholder: "E.g., Rust, Smart-Contracts."
  
  - type: textarea
    id: directory_path
    attributes:
      label: "Particular directory path for the template."
      placeholder: "template/Data-Science/Time-Series-Forecasting/LSTM-Stock-Prediction/"
  
  - type: textarea
    id: tech_stack
    attributes:
      label: "What tech stacks do you want to include?"
      placeholder: "E.g., React, Node.js, Express, MongoDB"

  - type: textarea
    id: brief_description
    attributes:
      label: "Brief Description"
      placeholder: "Describe what the template is about, how it functions, and how beneficial it will be for users to scaffold using the 'universal-box init' command."
      
  - type: checkbox
    id: check_previous_requests
    attributes:
      label: "👀 Have you spent some time checking if this issue has been raised before?"
      options:
        - "Yes"
        - "No"
  
  - type: checkbox
    id: code_of_conduct
    attributes:
      label: "🏢 Have you read the Code of Conduct?"
      options:
        - "I have read the [Code of Conduct](https://github.com/Abhishek-Mallick/universal-box/blob/main/.github/CODE_OF_CONDUCT.md)"
    validations:
      required: true
  
  - type: dropdown
    id: work_on_issue
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
